name: Stuff Bear Likes
favicon: null
layout_spectrum: 0.27817738917656243
typography_spectrum: 0.08704925957135856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.48882863903418183
  lightness: 0.14639049512334168
  saturation: 0.893513360992074
  rhythmicContrast: 0.1291442688088864
purpose: []
