name: Stuff Bear Likes
favicon: null
layout_spectrum: 0.27817738917656243
typography_spectrum: 0.14022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cdcdcd'
    - '#104d94'
    - '#6c6e6c'
    - '#000000'
  brandStrength: 0.48882863903418183
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
